#!/usr/bin/env python3
"""Coverage guardrail script.

Enforces:
- Minimum overall coverage (configured via --min or pyproject fail_under fallback).
- No decrease vs stored baseline file (coverage_baseline.txt) unless within tolerance.
Usage:
  python scripts/coverage_guard.py --min 85 --tolerance 0.25
Baseline file stores last passing overall % (float).
"""
from __future__ import annotations
import argparse
import pathlib
import sys
import json

BASELINE_FILE = pathlib.Path("coverage_baseline.txt")
COVERAGE_JSON = pathlib.Path("coverage.json")  # generated by `coverage json` after tests

def load_current() -> float:
    if not COVERAGE_JSON.exists():
        print("ERROR: coverage.json not found. Run tests with coverage first.")
        return -1.0
    data = json.loads(COVERAGE_JSON.read_text(encoding="utf-8"))
    return float(data["totals"]["percent_covered"])

def load_baseline() -> float:
    if not BASELINE_FILE.exists():
        return -1.0
    try:
        return float(BASELINE_FILE.read_text(encoding="utf-8").strip())
    except ValueError:
        return -1.0

def save_baseline(pct: float) -> None:
    BASELINE_FILE.write_text(f"{pct:.2f}", encoding="utf-8")

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min", type=float, default=None, help="Minimum required coverage %")
    parser.add_argument("--tolerance", type=float, default=0.0, help="Allowed regression percentage")
    args = parser.parse_args()

    current = load_current()
    if current < 0:
        return 1
    baseline = load_baseline()

    target_min = args.min
    if target_min is None:
        # Try pyproject fail_under fallback by parsing pyproject (simplistic)
        pyproject = pathlib.Path("pyproject.toml")
        if pyproject.exists():
            for line in pyproject.read_text(encoding="utf-8").splitlines():
                if line.strip().startswith("fail_under"):
                    try:
                        target_min = float(line.split("=")[1].strip())
                    except Exception:
                        pass
    if target_min is None:
        target_min = 80.0

    errors = []
    if current < target_min:
        errors.append(f"Coverage {current:.2f}% below minimum {target_min:.2f}%")
    if baseline >= 0 and current + args.tolerance < baseline:
        errors.append(f"Coverage regression: was {baseline:.2f}% now {current:.2f}% (tolerance {args.tolerance}%)")

    if errors:
        print("COVERAGE GUARD FAIL:")
        for e in errors:
            print(" -", e)
        return 1

    # Update baseline if improved
    if current > baseline:
        save_baseline(current)
        print(f"Baseline updated to {current:.2f}%")
    else:
        print("Baseline unchanged.")
    print("Coverage guard passed.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
